"""initial_schema

Revision ID: da0b7e6349bc
Revises: 
Create Date: 2026-04-18 16:32:31.555580
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'da0b7e6349bc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('profile_submitted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('business_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('bin', sa.String(length=12), nullable=False),
    sa.Column('legal_entity_type', sa.String(length=20), nullable=False),
    sa.Column('vat_registered', sa.Boolean(), nullable=False),
    sa.Column('vat_certificate_number', sa.String(length=50), nullable=True),
    sa.Column('industry_sector', sa.String(length=100), nullable=False),
    sa.Column('business_scope', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('products_services', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('volume_requirements', sa.Text(), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=True),
    sa.Column('quality_standards', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('delivery_requirements', sa.Text(), nullable=True),
    sa.Column('annual_revenue_range', sa.String(length=30), nullable=True),
    sa.Column('growth_target', sa.Text(), nullable=True),
    sa.Column('operating_regions', postgresql.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('willing_cross_border', sa.Boolean(), nullable=True),
    sa.Column('preferred_partner_profile', sa.Text(), nullable=True),
    sa.Column('exclusion_criteria', sa.Text(), nullable=True),
    sa.Column('embedding_generated', sa.Boolean(), nullable=False),
    sa.Column('demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_profiles_user_id'), 'business_profiles', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_business_profiles_user_id'), table_name='business_profiles')
    op.drop_table('business_profiles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
